### ISSUE TITLE
Ability to configure permissions

### ISSUE THREAD

**Issue by baurmatt** [cirrax/puppet-libvirt#13]
We need to be able to configure the storage pool permissions as described in https://libvirt.org/formatstorage.html#StoragePoolTarget. I'm thinking about adding the parameters owner|group|mode to libvirt_pool, what do you think?

**Comment by trefzer** [comment]
that's fine for me, go ahead. I would appreciate the parameters not beeing mandatory. So we can keep with the libvirt default mechanism.
