### ISSUE TITLE
Add ability to configure '/etc/libvirt/libvirtd.conf'

### ISSUE THREAD

**Issue by kBite** [cirrax/puppet-libvirt#32]
To my understanding it's not yet possible to configure values in `/etc/libvirt/libvirtd.conf`. File format looks a lot like `qemu.conf`: https://github.com/libvirt/libvirt/blob/master/src/remote/libvirtd.conf

I guess, adding the ability to configure `/etc/libvirt/libvirtd.conf` should be analogue to `qemu_conf`. If I didn't miss something crucial here, I might be able to come up with a PR in the next days.

**Comment by trefzer** [comment]
Yes you're right, this cannot be configured currently.
I would prefer a type and a provider like done for /etc/default/libvirtd (/etc/sysconfig/libvirtd on redhat). This should be quite simply to implement (look at lib/puppet/provider/libvirtd_default and lib/puppet/type/libvirtd_default.rb.
For proper documentation look at: https://forge.puppet.com/puppetlabs/inifile

**Comment by kBite** [comment]
I'm quite sure https://github.com/libvirt/libvirt/blob/master/src/remote/libvirtd.conf is no inifile config, but more like `qemu.conf`. That's why I took `qemu_conf` as reference instead.

I'm not sure how a new type and provider will help. Please see #33

**Comment by trefzer** [comment]
well it's not an inifile per se, but /etc/default/libvirtd isn't either, but can be configured accordingly. 
The good thing with inifile module is, it does not overwrite the original file but adapt the parameters in the right place (below the comment). which I think is a verry nice feature.

But I will look at your suggestion, but I need some time to do so.

**Comment by kBite** [comment]
Hey,

did you have some time to have a look? The only thing different than `qemu_conf` is the parameters name and `or ( !!(value =~ /^".*"$/) )` in it's template.

This allows to configure double quoted integers necessary for the options 'tls_port', 'tcp_port', 'unix_sock_ro_perms', 'unix_sock_rw_perms', and 'unix_sock_admin_perms'.

The port options allow numbers and service names, so their value is expected as string by libvirtd.

Hiera example:
```   
    libvirt::libvirtd_conf:
      tcp_port: '"16509"'
      unix_sock_ro_perms: '"0770"'
```

**Comment by trefzer** [comment]
see above commit, which implements the same, without template.
I favor using the type/provider approach in above commit, since it does not alter the whole config file but only the parameters changed.
Could you test ? (it's in the dev_pdk branch, which I like to merge soon).

**Comment by kBite** [comment]
Using `dev_pdk` with Hiera looking like
```
libvirt::libvirtd_conf:
  unix_sock_ro_perms: '"0770"'
  unix_sock_rw_perms: '"0770"'
  unix_sock_admin_perms: '"0770"'
  max_client_requests: '100'
  admin_max_client_requests: '100'
  log_filters: '2:qemu.qemu_events 2:qemu.qemu_bitmaps_ops'
  host_uuid_source: 'machine-id'
  keepalive_interval: '30'
  keepalive_count: '20'
```
Resulting in `libvirtd.conf` to look like
```
# cat libvirtd.conf
unix_sock_ro_perms = "0770"
unix_sock_rw_perms = "0770"
unix_sock_admin_perms = "0770"
max_client_requests = 100
admin_max_client_requests = 100
log_filters = 2:qemu.qemu_events 2:qemu.qemu_bitmaps_ops
host_uuid_source = machine-id
keepalive_interval = 30
keepalive_count = 20
```
Strings must be quoted. I could workaround this by doing something like ...
```
  log_filters: '"2:qemu.qemu_events 2:qemu.qemu_bitmaps_ops"'
```
... but that's not what I'd expect.

**Comment by trefzer** [comment]
could you please test the commit above ?
quoting should now not be necessary any more and arrays should also be handled correctly.

so your hiera should now look:
```
libvirt::libvirtd_conf:
  unix_sock_ro_perms: '0770'
  unix_sock_rw_perms: '0770'
  unix_sock_admin_perms: '0770'
  max_client_requests: 100
  admin_max_client_requests: 100
  log_filters: '2:qemu.qemu_events 2:qemu.qemu_bitmaps_ops'
  host_uuid_source: 'machine-id'
  keepalive_interval: 30
  keepalive_count: 20

  sasl_allowed_username_list:
     - 'joe@EXAMPLE.COM'
     - 'fred@EXAMPLE.COM'
```

**Comment by kBite** [comment]
6197cc7 writes `libvirtd.conf` as expected :+1: 
```
libvirt::libvirtd_conf:
  unix_sock_ro_perms: '0770'
  unix_sock_rw_perms: '0770'
  unix_sock_admin_perms: '0770'
  max_client_requests: 100
  admin_max_client_requests: 100
  log_filters: '2:qemu.qemu_events 2:qemu.qemu_bitmaps_ops'
  host_uuid_source: 'machine-id'
  keepalive_interval: 30
  keepalive_count: 20
```
```
# cat libvirtd.conf
unix_sock_ro_perms = "0770"
unix_sock_rw_perms = "0770"
unix_sock_admin_perms = "0770"
max_client_requests = 100
admin_max_client_requests = 100
log_filters = "2:qemu.qemu_events 2:qemu.qemu_bitmaps_ops"
host_uuid_source = "machine-id"
keepalive_interval = 30
keepalive_count = 20
```

**Comment by kBite** [comment]
> Whats yet missing is a notify to the libvirtd service
Notifying libvirtd should be optional as it would affect running VMs depending on the overall setup.

Maybe something like `libvirtd_notify: boolean`?

**Comment by trefzer** [comment]
Added the notification, think will merge this.
I cannot see any libvirtd.conf setting, that affects a VM. It's safe to restart the service if puppet manages the service to activate the settings.

**Comment by kBite** [comment]
> I cannot see any libvirtd.conf setting, that affects a VM.
Nevermind, confused `libvirtd` with `qemu` :woman_shrugging:

> It's safe to restart the service if puppet manages the service to activate the settings.
Yes, seems fine then

**Comment by trefzer** [comment]
ok. will release now. 
Thanks a lot for help testing (and the initial code )
Greetings
