### ISSUE TITLE
Circular Dependency when drop_default_net == true

### ISSUE THREAD

**Issue by tparkercbn** [cirrax/puppet-libvirt#36]
Error: Found 1 dependency cycle:
(Anchor[libvirt::installed] => Exec[libvirt-delete-network-default] => Libvirt::Network[default] => Class[Libvirt::Config] => Class[Libvirt::Service] => Service[libvirtd] => Class[Libvirt::Service] => Anchor[libvirt::installed])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph

**Comment by trefzer** [comment]
could you please test this pull request ? it add spec tests for dependency, and should fix the loop. If ok, I will release.

**Comment by tparkercbn** [comment]
Works perfectly!  Thank you for the quick fix!
