### ISSUE TITLE
Support for UEFI Boot Loader

### ISSUE THREAD

**Issue by cs-werbung** [cirrax/puppet-libvirt#49]
Hi,

I would like to have the possibility to add a `<loader>` like in the following example:

`<domain type='kvm'>
  <name>redhat</name>
  <uuid>fc3eeb3e-f87e-4042-8426-fabed2bcb23d</uuid>
  <memory unit='KiB'>1048576</memory>
  <currentMemory unit='KiB'>1048576</currentMemory>
  <vcpu placement='static'>4</vcpu>
  <os>
    <type arch='x86_64' machine='pc-i440fx-rhel7.0.0'>hvm</type>
    <loader type='rom'>/usr/share/edk2.git/ovmf-x64/OVMF_CODE-pure-efi.fd</loader>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>`

**Comment by trefzer** [comment]
This is possible with the current code !

**Comment by cs-werbung** [comment]
@trefzer can you elaborate how this would work? I haven't found anything in the documentation.
