### ISSUE TITLE
Using libvirtd_default type fails on redhat based systems.

### ISSUE THREAD

**Issue by rwf14f** [cirrax/puppet-libvirt#50]
Trying to set options in /etc/sysconfig/libvirtd on CentOS 7 using the default_conf hash fails with the following error message:
> Error: /Stage[main]/Libvirt::Config/Libvirtd_default[LIBVIRTD_ARGS]: Could not evaluate: No ability to determine if libvirtd_default exists

The problem was introduced with PR #41 ([fix libvirtd_default and update pdk #41](https://github.com/cirrax/puppet-libvirt/pull/41/commits/aa1cb07b9809ace0c51fa7b84742e1ead4f540f7)). Changing `:debian` back to `:ini_settings` in _ini_settings.rb_ solves it (tested only on CentOS 7 though).

**Comment by trefzer** [comment]
This is strange !
question: in which file did he write LIBVIRTD_ARGS (either /etc/default/libvirtd or /etc/sysconfig/libvirtd) ?
because if you only changed the debian setting, I would expect, that /etc/default/libvirtd was changed which is useless on centos since  /etc/sysconfig/libvirtd should be used.

**Comment by rwf14f** [comment]
It was written to /etc/sysconfig/libvirtd.
Here's my understanding of the problem:
The error is caused by the redhat specific code not finding the parent that is defined in _ini_settings_redhat.rb_ (`Puppet::Type.type(:libvirtd_default).provider(:ini_setting)`), as this is now named `:debian`. An alternative fix would be to change the parent to `Puppet::Type.type(:libvirtd_default).provider(:debian)`, but this also requires to rename _ini_settings.rb_ to _debian.rb_.
I'd revert the change in _ini_settings.rb_ from `:debian` to `:ini_settings` and see it as a common base, which currently matches what's required on Debian and not as a Debian specific implementation.

**Comment by trefzer** [comment]
uups already closed ;)
@rwf14f I understand it the same way ! 
and I just uploaded a new version v4.3.2 which fixes the issue give me some minutes to also push it to forge.

Thank you for the issue !
