### ISSUE TITLE
Value Conversion Error

### ISSUE THREAD

**Issue by REHICode** [cirrax/puppet-libvirt#51]
Hi, i wanted to update my code to your module version v4.3.2 from the previous v4.3.1.

My libvirt configuration in a control-repo profile looks like this:
```
# configure libvirt
  class { 'libvirt':
    libvirt_package_names => $required_packages,
    service_name          => 'libvirtd.service', # is valid for Ubuntu xenial, bionic and focal
    libvirtd_conf         => {
      listen_tls         => 0,
      listen_tcp         => 1,
      tcp_port           => '16509',
      unix_sock_group    => $kvm_unixsockgroup,
      unix_sock_rw_perms => '0770',
      auth_unix_ro       => 'none',
      auth_unix_rw       => 'none',
      auth_tcp           => 'none',
    },
    qemu_conf             => {
      vnc_listen => '::',
      vnc_tls    => 0,
    }
  }

```

Running puppet on my KVM-Host i get this error message now:
`Error: Failed to apply catalog: Parameter value failed on Libvirtd_conf[listen_tls]: Munging failed for value 0 in class value: no implicit conversion of Integer into String (file: /etc/puppetlabs/code/environments/EBN19876Upstreamupdates/modules/libvirt/manifests/config.pp, line: 71)`

Also in the /etc/libvirt/libvirtd.conf from ubuntu the integer seems to be intended:
```
root@machine01:~# cat /etc/libvirt/libvirtd.conf | grep -C8 '#listen_tls'
# Flag listening for secure TLS connections on the public TCP/IP port.
# NB, must pass the --listen flag to the libvirtd process for this to
# have any effect.
#
# It is necessary to setup a CA and issue server certificates before
# using this capability.
#
# This is enabled by default, uncomment this to disable it
#listen_tls = 0
listen_tls = 0

...
```

Could you please help me with this issue?

Kind Regards
Rene Hirrich

**Comment by REHICode** [comment]
Hi, the reason for the error above is this commit:
https://github.com/cirrax/puppet-libvirt/commit/10a67b9a3e0ac4fb4e78250cb573ad20c454826f
in file: lib/puppet/type/libvirtd_conf.rb

Could you please fix or revert the change?
Thank you

**Comment by chrisongthb** [comment]
Same problem here for v4.3.3:
```
[…]
Error: Failed to apply catalog: Parameter value failed on Libvirtd_conf[listen_tls]: Munging failed for value 0 in class value: no implicit conversion of Integer into String (file: /etc/puppetlabs/code/environments/…/modules/libvirt/manifests/config.pp, line: 71) 
[…]
```
Latest working version for us is v4.3.1. Please fix, thanks! :)

**Comment by REHICode** [comment]
works like a charm, thank you
