### ISSUE TITLE
Modular services

### ISSUE THREAD

**Issue by jcpunk** [cirrax/puppet-libvirt#57]
RHEL9+ are recommending the more loosely linked services: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/optimizing-virtual-machine-performance-in-rhel_configuring-and-managing-virtualization#proc_enabling-modular-libvirt-daemons_assembly_optimizing-libvirt-daemons

Is this something than can be integrated?

**Comment by silug** [comment]
https://github.com/cirrax/puppet-libvirt/pull/58 has some changes that follow the documentation, but at the moment it is entirely untested.

**Comment by silug** [comment]
> #58 has some changes that follow the documentation, but at the moment it is entirely untested.

Reading the documentation again, it looks like the configuration is also spread out to different files, so I suspect this change will require a lot more effort.
