### ISSUE TITLE
Storage pool support

### ISSUE THREAD

**Issue by maxenced** [cirrax/puppet-libvirt#7]
I open this issue to discuss storage pool support.

It is currently supported by thias/libvirt (which is not maintained anymore) : 

* Provider : https://github.com/thias/puppet-libvirt/blob/master/lib/puppet/provider/libvirt_pool/virsh.rb
* Type : https://github.com/thias/puppet-libvirt/blob/master/lib/puppet/type/libvirt_pool.rb

I guess we could just rely on it to start supporting pool (GPL / Apache 2 should accept it as long as credit is given to thias ). 

What do you think about it ?

**Comment by trefzer** [comment]
+1
Great idea.
Probably we could base other resources (eg secrets, networks etc.) on this code too.

**Comment by maxenced** [comment]
Yep. Let's wait for #4 and #6 to be merged, and I'll create a  new branch to start working on this

**Comment by trefzer** [comment]
@maxenced thanks for your work,
seems to be done.
